### ISSUE TITLE
Implement authorized VP-Request

### ISSUE THREAD

**Issue by OSchlienz** [eclipse-tractusx/managed-identity-wallet#242]
- [x] implement token validation & authorization #244 
- [x] update DIDdocument: include credential service: https://github.com/eclipse-tractusx/identity-trust/blob/main/specifications/verifiable.presentation.protocol.md#6-cs-endpoint-resolution-through-did-documents (and additional reuirements architecture) #243 
- [x] implement matching of authorized credential types to available VCs in wallet (https://github.com/eclipse-tractusx/tractusx-profiles/blob/main/cx/policy/specs/policy.mapping.md) #130
- [x] VP generation for previously authorized credentials 
- [x] Add check for jti (create new table and logic) #264
